website/views.py
from flask import Blueprint, render_template, request
from flask.helpers import flash
from flask_login import login_required, current_user
import website.calculating.functions as f

views = Blueprint('views', __name__)

@views.route('/')
@login_required
def home():
    return render_template("calculate.html", user=current_user)


@views.route("/calc_zone", methods=["GET", "POST"])
@login_required
def calc_zone():
    res = ''
    if request.method == 'POST':
        zone = request.form.get('zoneNumber')
        distance = request.form.get('distance')
        direction = request.form.get('direction')
        if zone:
            if distance:
                if direction:
                    try:
                        zone = int(zone)
                    except Exception:
                        flash("Зона повинна бути цілим додатнім числом", category='error')
                    else:
                        try:
                            distance = float(distance)
                        except Exception:
                            flash('Відстань може бути лише цілим або дробовим додатнім числом', category='error')
                        else:
                            try:
                                res = f.y_value_for_zones(zone, distance, direction)
                            except Exception as e:
                                flash(f'{e}', category="error")
                else:
                    flash("Введіть напрям", category="error")
            else:
                flash("Введіть відстань", category="error")
        else:
            flash("Введіть номер зони", category="error")
    return render_template('calc/zone.html', user=current_user, res=res)


@views.route('/calc_map_accuracy', methods=["GET", "POST"])
@login_required
def calc_map_accuracy():
    res = ''
    if request.method == "POST":
        scale = request.form.get('scale')
        if scale:
            try:
                scale = scale.replace(' ', '')
                scale = int(scale)
            except Exception as e:
                flash('Масштаб повинен бути цілим додатнім числом', category="error") 
            else:
                try:
                    res = f.accuracy_of_scale(scale)
                except Exception as e:
                    flash(f"{e}", category="error")
        else:
            flash('Введіть масштаб', category="error")
    return render_template('calc/map_accuracy.html', user=current_user, res=res)


@views.route('/calc_segmentation', methods=["GET", "POST"])
@login_required
def calc_segmentation():
    res=''
    if request.method == 'POST':
        segment = request.form.get('segment')
        try:
            scale = f.get_scale_from_segment(segment)
        except Exception as e:
            flash(f'{e}', category='error')
        else:
            res = scale
    return render_template('calc/segmentation.html', user=current_user, res=res)


@views.route('/calc_dividing', methods=["GET", "POST"])
@login_required
def calc_dividing():
    res = ''
    if request.method == "POST":
        dividing_scale = request.form.get('dividing1')
        divider_scale = request.form.get('dividing2')
        if dividing_scale:
            if divider_scale:
                try:
                    res = f.divide_scales(dividing_scale, divider_scale)
                except Exception as e:
                    flash(f"{e}", category="error")
            else:
                flash('Введіть Масштаб Трапеції, Що Потрібно Отримати В Результаті Ділення', category="error")
        else:
            flash('Введіть Масштаб Трапеції, Що Ділиться', category="error")
    return render_template('calc/dividing.html', user=current_user, res=res)


@views.route('/calc_size', methods=["GET", "POST"])
@login_required
def calc_size():
    res = ''
    if request.method == 'POST':
        b = request.form.get('b')
        l = request.form.get('l')
        if b:
            if l:
                try:
                    res = f.scale_from_size(b, l)
                except Exception as e:
                    flash(f'{e}')
            else:
                flash('Введіть ΔL')
        else:
            flash('Введіть ΔL')
    return render_template('calc/size.html', user=current_user, res=res)

website/templates/calc/dividing.html
{% extends 'base.html' %} {% block title %}Масштаб{% endblock %} {% block
content %}
<h3 align="center">Ділення Трапецій</h3>
<form
  name="dividing"
  action="{{ url_for('views.calc_dividing') }}"
  method="post"
  autocomplete="off"
>
  <div class="form-group">
    <label for="dividing1">Трапеція, Яка Ділиться</label>
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">1 :</span>
      </div>
      <input
        type="text"
        class="form-control"
        id="dividing1"
        name="dividing1"
        placeholder="1 000 000"
      />
    </div>
  </div>
  <div class="form-group">
    <label for="dividing2">Трапеція, Яку Потрібно Отримати Після Ділення</label>
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">1 :</span>
      </div>
      <input
        type="text"
        class="form-control"
        id="dividing2"
        name="dividing2"
        placeholder="200 000"
      />
    </div>
  </div>
  <div
    class="p-3 mb-2 bg-success text-white rounded"
    style="white-space: pre-line"
  >Відповідь: {{ res }}
  </div>
  <hr />
  <a class="btn btn-secondary" href="/" role="button">Назад</a>
  <button type="submit" class="btn btn-primary">Порахувати</button>
</form>
{% endblock %}

website/templates/calc/map_accuracy.html
{% extends 'base.html' %} {% block title %}Точність{% endblock %} {% block
content %}
<h3 align="center">Точність Маcштабу Карти</h3>
<form
  name="scaleForm"
  action="{{ url_for('views.calc_map_accuracy') }}"
  method="post"
  autocomplete="off"
>
  <label for="basic-url">Масштаб</label>
  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon1">1 :</span>
    </div>
    <input
      type="text"
      class="form-control"
      placeholder="500"
      id="scale"
      name="scale"
    />
  </div>
  <div
    class="p-3 mb-2 bg-success text-white rounded"
    style="white-space: pre-line"
  >Відповідь: {{ res }}</div>
  <hr />
  <a class="btn btn-secondary" href="/" role="button">Назад</a>
  <button type="submit" class="btn btn-primary">Порахувати</button>
</form>
{% endblock %}

website/templates/calc/segmentation.html
{% extends 'base.html' %} {% block title %}Масштаб{% endblock %} {% block
content %}
<h3 align="center">Масштаб Карти Через Номенклатуру</h3>
<form
  name="segmentation"
  action="{{ url_for('views.calc_segmentation') }}"
  method="post"
  autocomplete="off"
>
  <div class="form-group">
    <label for="segment">Номенклатура Карти</label>
    <input
      type="text"
      class="form-control"
      id="segment"
      name="segment"
      placeholder="L–35–35–А–а"
    />
  </div>
  <div class="p-3 mb-2 bg-success text-white rounded" style="white-space: pre-line">Відповідь: {{ res }}</div>
  <hr />
  <a class="btn btn-secondary" href="/" role="button">Назад</a>
  <button type="submit" class="btn btn-primary">Порахувати</button>
</form>
{% endblock %}

website/templates/calc/size.html
{% extends 'base.html' %} {% block title %}Масштаб{% endblock %} {% block content
%}
<h3 align="center">Розміри Трапецій</h3>
<form
  name="size"
  action="{{ url_for('views.calc_size') }}"
  method="post"
  autocomplete="off"
>
  <div class="form-group">
    <label for="b">ΔВ</label>
    <div class="input-group mb-3">
      <input
        type="text"
        class="form-control"
        id="b"
        name="b"
        placeholder="0º0'25'' = 0 0 25"
      />
    </div>
  </div>
  <div class="form-group">
    <label for="l">ΔL</label>
    <div class="input-group mb-3">
      <input
        type="text"
        class="form-control"
        id="l"
        name="l"
        placeholder="0º0'37.5'' = 0 0 37.5"
      />
    </div>
  </div>
  <p>Градуси Вводити Через Пробіл</p>
  <div
    class="p-3 mb-2 bg-success text-white rounded"
    style="white-space: pre-line"
  >Відповідь: {{ res }}
  </div>
  <hr />
  <a class="btn btn-secondary" href="/" role="button">Назад</a>
  <button type="submit" class="btn btn-primary">Порахувати</button>
</form>
{% endblock %}

website/templates/calc/zone.html
{% extends 'base.html' %} {% block title %}Обчислити{% endblock %} {% block
content %}
<h3 align="center">Значення Ординати Точĸи</h3>
<form
  name="zoneForm"
  action="{{ url_for('views.calc_zone') }}"
  method="post"
  autocomplete="off"
>
  <div class="form-group">
    <label for="zoneNumber">Номер Зони/Колони</label>
    <input
      type="text"
      class="form-control"
      id="zoneNumber"
      name="zoneNumber"
      placeholder="15"
    />
  </div>
  <div class="form-group">
    <label for="distance">Відстань Від Меридіану</label>
    <input
      type="text"
      class="form-control"
      id="distance"
      name="distance"
      placeholder="333333"
    />
  </div>
  <div class="form-group">
    <label for="direction">Напрямок</label>
    <input
      type="text"
      class="form-control"
      id="direction"
      name="direction"
      placeholder="Захід Або Схід"
    />
  </div>
  <div class="p-3 mb-2 bg-success text-white rounded" style="white-space: pre-line">Відповідь: {{ res }}</div>
  <hr />
  <a class="btn btn-secondary" href="/" role="button">Назад</a>
  <button type="submit" class="btn btn-primary">Порахувати</button>
</form>
{% endblock %}